# Generated by Django 3.2.5 on 2021-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='image_url',
        ),
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
