# Generated by Django 3.2.5 on 2021-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0002_auto_20210709_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='fashon',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='lake',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='station',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='image_url',
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fashon',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lake',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trend',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
