# Generated by Django 3.2.5 on 2021-07-09 17:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0003_auto_20210709_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/animals'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='fashon',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/fashons'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/hotels'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='lake',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/lakes'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/markets'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/schools'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/sports'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/animals'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='trend',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/trends'), upload_to=''),
        ),
    ]
