# Generated by Django 3.2.5 on 2021-07-09 18:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0004_auto_20210709_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.FileField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='static/images/markets')),
        ),
    ]
