# Generated by Django 3.2.5 on 2021-07-09 18:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0005_alter_market_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.FileField(null=True, upload_to=django.core.files.storage.FileSystemStorage(location='images')),
        ),
    ]
