# Generated by Django 3.1.7 on 2021-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0008_auto_20210712_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=2083)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
