# Generated by Django 3.1.7 on 2021-07-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0009_hospital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='WildLife',
        ),
    ]
