# Generated by Django 3.1.7 on 2021-07-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0010_auto_20210712_1735'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fashon',
            table='Fashons',
        ),
        migrations.AlterModelTable(
            name='hospital',
            table='Hospitals',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='Hotels',
        ),
        migrations.AlterModelTable(
            name='lake',
            table='Lakes',
        ),
        migrations.AlterModelTable(
            name='market',
            table='Markets',
        ),
        migrations.AlterModelTable(
            name='school',
            table='Schools',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='Sports',
        ),
        migrations.AlterModelTable(
            name='station',
            table='Stations',
        ),
        migrations.AlterModelTable(
            name='trend',
            table='Trends',
        ),
        migrations.AlterModelTable(
            name='wildlife',
            table='Wildlife',
        ),
    ]
