# Generated by Django 3.1.7 on 2021-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0011_auto_20210712_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=2083)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
            options={
                'db_table': 'Tourism',
            },
        ),
        migrations.AlterModelOptions(
            name='fashon',
            options={'verbose_name': 'Fashon List'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel List'},
        ),
    ]
