# Generated by Django 3.1.7 on 2021-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0013_auto_20210831_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
    ]
