# Generated by Django 3.1.7 on 2021-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kongoni_web', '0014_auto_20210901_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fashon',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wildlife',
            name='image',
            field=models.ImageField(blank='False', null=True, upload_to=''),
        ),
    ]
